config/routes.rb
Rails.application.routes.draw do
  resources :gamers
  root :to => "rounds#new"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/rounds/new', to: 'rounds#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bet.rb
class Bet < ApplicationRecord
  #structure
  	#t.string   "choice"
    #t.integer  "amount"
    #t.integer  "amount_won"
    #t.integer  "gamer_id"
    #t.integer  "round_id"
    #t.datetime "created_at", null: false
    #t.datetime "updated_at", null: false

  belongs_to :gamer
  belongs_to :round
end

app/models/gamer.rb
class Gamer < ApplicationRecord
	#structure
		#t.string   "first_name"
	    #t.string   "last_name"
	    #t.string   "gender"
	    #t.date     "born_date"
	    #t.datetime "created_at", null: false
	    #t.datetime "updated_at", null: false
	
	has_one :wallet, dependent: :destroy
	has_many :bets

	accepts_nested_attributes_for :wallet

	after_create :set_money

	# show a full name for gamer
	def full_name
		if self.first_name && self.last_name
			self.first_name + " " + self.last_name
		elsif self.last_name
			self.last_name
		elsif self.first_name
			self.first_name
		else
			""
		end
	end

	# get all gamer with money for bets
	def self.gamer_with_money 
		self.joins('join wallets w on gamers.id = w.gamer_id').where('w.money > 0')
	end 

	private
	# set default money for new gamer
	def set_money
		wallet = Wallet.new()
		wallet.gamer_id = self.id
		wallet.money = 10000
		wallet.save
	end
end

app/models/round.rb
class Round < ApplicationRecord
	#structure
	#t.string   "result"
    #t.datetime "created_at", null: false
    #t.datetime "updated_at", null: false

    has_many :bets
end

app/models/wallet.rb
class Wallet < ApplicationRecord
  #structure
  #t.integer  "money"
  #t.integer  "gamer_id"
  #t.datetime "created_at", null: false
  #t.datetime "updated_at", null: false
  
  belongs_to :gamer
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/gamers_controller.rb
class GamersController < ApplicationController
  before_action :set_gamer, only: [:show, :edit, :update, :destroy]

  # GET /gamers
  # GET /gamers.json
  def index
    @gamers = Gamer.all
  end

  # GET /gamers/1
  # GET /gamers/1.json
  def show
  end

  # GET /gamers/new
  def new
    @gamer = Gamer.new
  end

  # GET /gamers/1/edit
  def edit
  end

  # POST /gamers
  # POST /gamers.json
  def create
    @gamer = Gamer.new(gamer_params)

    respond_to do |format|
      if @gamer.save
        format.html { redirect_to @gamer, notice: 'Gamer was successfully created.' }
        format.json { render :show, status: :created, location: @gamer }
      else
        format.html { render :new }
        format.json { render json: @gamer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gamers/1
  # PATCH/PUT /gamers/1.json
  def update
    respond_to do |format|
      if @gamer.update(gamer_params)
        format.html { redirect_to @gamer, notice: 'Gamer was successfully updated.' }
        format.json { render :show, status: :ok, location: @gamer }
      else
        format.html { render :edit }
        format.json { render json: @gamer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gamers/1
  # DELETE /gamers/1.json
  def destroy
    @gamer.destroy
    respond_to do |format|
      format.html { redirect_to gamers_url, notice: 'Gamer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gamer
      @gamer = Gamer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gamer_params
      params.require(:gamer).permit(:first_name, :last_name, :gender, :born_date)
    end
end

app/controllers/rounds_controller.rb
class RoundsController < ApplicationController
	require 'open-uri'

	@@top_bets_percentage = 0.15
	@@floor_bets_percentage = 0.08
	@@container_bets = []

	def new
		@rounds = Round.all
	end

	def create
		gamer_bets
		if @@container_bets.any?
			@round = Round.new
			@round.result = get_color
			@round.save
			@@container_bets.each do |bet|
				bet.round_id = @round.id
				bet.amount_won = pay_win(bet, @round.result)
				bet.save
			end
			respond_to do |format|
				format.html { render :new, notice: 'Resultado de la ronda.' }
			end
		else
			respond_to do |format|
				format.html { render :new, notice: 'Ningún jugador aposto a esta ronda por falta de dinero.' }
			end
		end
	end

	def get_color #generate rand color for the game
		result = rand(1..100).round(2).to_i
		case result
		when 1..2 #probability for green color 2%
			"green"
		when 3..51 #probability for red color 49%
			"red"
		else #probability for black color 49%
			"black"
		end
	end

	private

	#get weather for the next week
	def get_weather
		bet_discrete = false
		weather_response = open('https://api.darksky.net/forecast/9997fed57baa9664ce7817037eed5024/-33.4449336,-70.6568987?lang=es&units=si&exclude=currently,minutely,hourly,alerts,flags')
		response_string = ""
		weather_response.each do |line|
		  response_string << line
		end
		weather = JSON.parse(response_string)

		weather["daily"]['data'].each do |day|
			if day['temperatureMax'] > 29
				bet_discrete = true
			end
		end
		bets_percentage(bet_discrete)
	end

	#change percentage limits for bets if weather conditions are true
	def bets_percentage bet_discrete
		@@top_bets_percentage = 0.10 if bet_discrete
		@@floor_bets_percentage = 0.04 if bet_discrete
	end

	# create bet gamer for current round
	def gamer_bets
		get_weather
		@gamers = Gamer.gamer_with_money
		@@container_bets = []
		@gamers.each do |gamer|
			bet = Bet.new
			bet.gamer_id = gamer.id
			if gamer.wallet.money > 1000
				bets_percentage_choice = rand(@@floor_bets_percentage..@@top_bets_percentage).round(2)
				bet.amount = gamer.wallet.money * bets_percentage_choice
			else
				bet.mount = gamer.wallet.money
			end
			bet.choice = get_color
			@@container_bets << bet
		end
	end

	def pay_win(bet, result)
		if bet.choice == result
			case result
			when "red", "black" 
				bet.gamer.wallet.money += bet.amount*2
				won_amount = bet.amount*2
			else
				bet.gamer.wallet.money += bet.amount*15
				won_amount = bet.amount*15
			end
		else
			bet.gamer.wallet.money -= bet.amount
			won_amount = 0
		end
		bet.gamer.wallet.save
		return won_amount
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def number_to_currency number, options={}
		result = super(number, options)
		if result.present?
			result.delete!(" ")
		end
		return result
	end
end

app/helpers/gamers_helper.rb
module GamersHelper
end

app/helpers/rounds_helper.rb
module RoundsHelper
end

app/views/gamers/_form.html.erb
<%= form_for(gamer) do |f| %>
  <% if gamer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(gamer.errors.count, "error") %> prohibited this gamer from being saved:</h2>

      <ul>
      <% gamer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name, "Nombre" %>
    <%= f.text_field :first_name %>
  </div>

  <div class="field">
    <%= f.label :last_name, "Apellido" %>
    <%= f.text_field :last_name %>
  </div>

  <div class="field">
    <%= f.label :gender, "Género" %>
    <%= f.text_field :gender %>
  </div>

  <div class="field">
    <%= f.label :born_date, "Fecha de nacimiento" %>
    <%= f.date_select :born_date, start_year: 1910, end_year: Date.today.year %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/gamers/edit.html.erb
<h1>Editing Gamer</h1>

<%= render 'form', gamer: @gamer %>

<%= link_to 'Show', @gamer %> |
<%= link_to 'Back', gamers_path %>

app/views/gamers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Gamers</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Género</th>
      <th>Fecha de nacimiento</th>
      <th>Edad</th>
      <th>Dinero</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @gamers.each do |gamer| %>
      <tr>
        <td><%= gamer.full_name %></td>
        <td><%= gamer.gender %></td>
        <td><%= gamer.born_date %></td>
        <td><%= Date.today.year - gamer.born_date.year %></td>
        <td><%= number_to_currency(gamer.wallet.money, precision: 2, strip_insignificant_zeros: true, separator:",", delimitier:".", ) %></td>
        <td><%= link_to 'Show', gamer %></td>
        <td><%= link_to 'Edit', edit_gamer_path(gamer) %></td>
        <td><%= link_to 'Destroy', gamer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Gamer', new_gamer_path %>

app/views/gamers/new.html.erb
<h1>New Gamer</h1>

<%= render 'form', gamer: @gamer %>

<%= link_to 'Back', gamers_path %>

app/views/gamers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @gamer.full_name %>
</p>

<p>
  <strong>Genero:</strong>
  <%= @gamer.gender %>
</p>

<p>
  <strong>Fecha de nacimiento:</strong>
  <%= @gamer.born_date %>
</p>

<p>
  <strong>Edad:</strong>
  <%= Date.today.year - @gamer.born_date.year %>
</p>

<p>
  <strong>Dinero disponible:</strong>
  <%= number_to_currency(@gamer.wallet.money, precision: 2, strip_insignificant_zeros: true, separator:",", delimitier:".", ) %>
</p>

<%= link_to 'Edit', edit_gamer_path(@gamer) %> |
<%= link_to 'Back', gamers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AmericanRoulette</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/rounds/new.html.erb
<h1>Rondas de juego</h1>

<a href="/rounds/create">Lanzar ronda</a>
<br>
<a href="<%= gamers_path%>">Jugadores</a>

<h2>Lista de rondas</h2>

<% if @rounds.any?%>
	<% @rounds.each do |round| %>
		<fieldset>
		<legend>Ronda</legend>
			<h3>Id: <%= round.id %></h3>
			<h4>Resultado: <%= round.result.capitalize %></h4>
			<p>Fecha: <%= round.created_at %></p>
			<h4>Apuestas:</h4>
			<table>
				<tr>
					<th>Nombre</th>
					<th>Color apostado</th>
					<th>Monto de apuesta</th>
					<th>Ganado en la ronda</th>
				</tr>
				<%if round.bets.any? %>
					<%round.bets.each do |bet| %>
						<tr>
							<td><%= bet.gamer.full_name %></td>
							<td><%= bet.choice %></td>
							<td><%= bet.amount %></td>
							<td><%= bet.amount_won %></td>
						</tr>
					<%end%>
				<%else%>
					<tr><td colspan="4">Nadie apostó en esta ronda</td></tr>
				<%end%>
			</table>
		</fieldset>
	<%end%>
<% else %>
	Aún no hay jugadas
<% end %>